# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

Department.create(name: "ビジネスカンパニー_コミュニケーションデザイン部", description: "")
Department.create(name: "ビジネスカンパニー_事業管理本部", description: "")
Department.create(name: "ビジネスカンパニー_営業戦略本部", description: "")
Department.create(name: "ビジネスカンパニー_SMB本部", description: "")
Department.create(name: "ビジネスカンパニー_事業推進本部_東京事業推進部", description: "")
Department.create(name: "ビジネスカンパニー_事業推進本部_北海道事業推進部", description: "")
Department.create(name: "ビジネスカンパニー_事業推進本部_関西事業推進部", description: "")
Department.create(name: "ビジネスカンパニー_事業推進本部_東海・北陸事業推進部", description: "")
Department.create(name: "ビジネスカンパニー_事業推進本部_広島事業推進部", description: "")
Department.create(name: "ビジネスカンパニー_事業推進本部_九州・沖縄事業推進部", description: "")
Department.create(name: "ビジネスカンパニー_事業推進本部_パートナービジネス部", description: "")
Department.create(name: "ビジネスカンパニー_事業推進本部_インサイドカスタマーサクセス部", description: "")
Department.create(name: "ビジネスカンパニー_Mid-Market本部_HRソリューション部", description: "")
Department.create(name: "ビジネスカンパニー_Mid-Market本部_Accounting/IPOソリューション部", description: "")
Department.create(name: "ビジネスカンパニー_InsideSales本部", description: "")
Department.create(name: "ビジネスカンパニー_CS本部_クラウドサポート部", description: "")
Department.create(name: "ビジネスカンパニー_CS本部_運用設計部", description: "")
Department.create(name: "ビジネスカンパニー_経理財務プロダクト本部_品質管理部", description: "")
Department.create(name: "ビジネスカンパニー_経理財務プロダクト本部_プロダクト開発部", description: "")
Department.create(name: "ビジネスカンパニー_HR_Product本部", description: "")
Department.create(name: "ビジネスカンパニー_クラウド横断本部", description: "")
Department.create(name: "ビジネスカンパニー_クラウド横断本部_UIテクノロジー部", description: "")
Department.create(name: "ビジネスカンパニー_クラウド横断本部_デザイン部", description: "")
Department.create(name: "ビジネスカンパニー_クラウド横断本部_京都開発部", description: "")
Department.create(name: "ビジネスカンパニー_クラウド経費本部_コミュニケーションデザイン部", description: "")
Department.create(name: "ビジネスカンパニー_クラウド経費本部_セールスディベロップメント部", description: "")
Department.create(name: "ビジネスカンパニー_クラウド経費本部_カスタマーサクセス部", description: "")
Department.create(name: "ビジネスカンパニー_クラウド経費本部_カスタマーサポート部", description: "")
Department.create(name: "ビジネスカンパニー_クラウド経費本部_開発部", description: "")
Department.create(name: "X本部_コンサルティング1部", description: "")
Department.create(name: "X本部_コンサルティング2部", description: "")
Department.create(name: "X本部_事業企画部", description: "")
Department.create(name: "X本部_サービス企画部", description: "")
Department.create(name: "X本部_UXデザイン部", description: "")
Department.create(name: "X本部_サービス開発部", description: "")
Department.create(name: "X本部_クライアントサービス開発部", description: "")
Department.create(name: "ホームカンパニー_PFM事業本部_プロダクトマネジメント部", description: "")
Department.create(name: "ホームカンパニー_PFM事業本部_マーケティング部", description: "")
Department.create(name: "ホームカンパニー_PFM事業本部_サービス開発部", description: "")
Department.create(name: "ホームカンパニー_PFM事業本部_ユーザーサポート部", description: "")
Department.create(name: "ホームカンパニー_PFM事業本部_事業開発部", description: "")
Department.create(name: "ホームカンパニー_メディア事業本部_ビジネスソリューション部", description: "")
Department.create(name: "ホームカンパニー_メディア事業本部_企画・開発部", description: "")
Department.create(name: "ホームカンパニー_メディア事業本部_編集部", description: "")
Department.create(name: "事業開発本部", description: "")
Department.create(name: "アカウントアグリゲーション本部", description: "")
Department.create(name: "Money Forward Lab本部", description: "")
Department.create(name: "CTO室", description: "")
Department.create(name: "京都開発本部", description: "")
Department.create(name: "CISO室", description: "")
Department.create(name: "サービス基盤本部", description: "")
Department.create(name: "経営企画本部", description: "")
Department.create(name: "財務経理本部", description: "")
Department.create(name: "分析推進室", description: "")
Department.create(name: "コーポレートディベロップメント室", description: "")
Department.create(name: "管理本部", description: "")
Department.create(name: "人事本部", description: "")
Department.create(name: "社長室", description: "")
Department.create(name: "Fintechリサーチ室", description: "")
Department.create(name: "内部監査室", description: "")
Department.create(name: "役員", description: "")
Department.create(name: "その他", description: "")

User.create(name: "井之上 裕樹", email: "inoue.yuki@moneyforward.co.jp", password: "11111111", password_confirmation: "11111111", admin: true, department_id: 20, manager: true)
User.create(name: "有働 卓真", email: "inoue.yuki+00000001@moneyforward.co.jp", password: "11111111", password_confirmation: "11111111", admin: false, department_id: 20, manager: false)
User.create(name: "長島 圭祐", email: "inoue.yuki+00000002@moneyforward.co.jp", password: "11111111", password_confirmation: "11111111", admin: false, department_id: 29, manager: true)
User.create(name: "宮本 大", email: "inoue.yuki+00000003@moneyforward.co.jp", password: "11111111", password_confirmation: "11111111", admin: true, department_id: 39, manager: false)
User.create(name: "蕭 詩穎", email: "inoue.yuki+00000004@moneyforward.co.jp", password: "11111111", password_confirmation: "11111111", admin: false, department_id: 48, manager: false)
User.create(name: "南立 拓矢", email: "inoue.yuki+00000005@moneyforward.co.jp", password: "11111111", password_confirmation: "11111111", admin: false, department_id: 20, manager: true)
User.create(name: "山下 侑哉", email: "inoue.yuki+00000006@moneyforward.co.jp", password: "11111111", password_confirmation: "11111111", admin: false, department_id: 20, manager: false)
User.create(name: "直江 友子", email: "inoue.yuki+00000007@moneyforward.co.jp", password: "11111111", password_confirmation: "11111111", admin: false, department_id: 20, manager: false)
User.create(name: "スティーブン・R・コヴィー", email: "inoue.yuki+00000008@moneyforward.co.jp", password: "11111111", password_confirmation: "11111111", admin: false, department_id: 62, manager: false)
User.create(name: "Diggy-MO", email: "inoue.yuki+00000009@moneyforward.co.jp", password: "11111111", password_confirmation: "11111111", admin: false, department_id: 20, manager: false)

Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 1)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 2)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 3)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 4)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 5)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 6)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 7)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 8)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 9)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 10)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 2, user_id: 1)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 2, anxiety: 1, user_id: 2)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 3)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 4)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 5)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 6)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 7)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 8)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 2, user_id: 9)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 10)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 1)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 2, anxiety: 2, user_id: 2)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 2, user_id: 3)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 4)
Questionnaire.create(mobility: 3, self_care: 1, usual_activities: 1, pain: 2, anxiety: 1, user_id: 5)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 6)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 7)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 8)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 9)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 10)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 2, user_id: 1)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 2)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 3)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 2, anxiety: 3, user_id: 4)
Questionnaire.create(mobility: 3, self_care: 1, usual_activities: 1, pain: 2, anxiety: 1, user_id: 5)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 6)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 7)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 8)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 9)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 10)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 3, user_id: 1)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 2, user_id: 2)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 3)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 2, anxiety: 1, user_id: 4)
Questionnaire.create(mobility: 3, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 5)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 2, user_id: 6)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 7)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 3, user_id: 8)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 9)
Questionnaire.create(mobility: 1, self_care: 1, usual_activities: 1, pain: 1, anxiety: 1, user_id: 10)
